---
title: Portfolio
output:
    html_document:
        toc: true
---

A lot of my recent work has been proprietary.
While most of it has not been under an NDA,
I feel it may be unethical to share certain details.

My work obviously has an aerospace theme, but please don't think of me as an "aerospace engineer".
I'm really an artist pretending to be a scientist pretending to be an engineer.
I just like solving problems which intersect many domains, and aerospace has a few of those problems.

## MegaHARP: Lots of Fancy Polarimetric Cameras in Space
This is the next evolution of the [HARP][HARP] instruments.
NASA Goddard reached out to us to do a study on the cost, performance,
and many other parameters of a polarimeter for an upcoming orbital observatory.
The result of my work was a basline design that will likely become the basis for their eventual request-for-proposals
and [ESI][ESI]'s corresponding proposal.
It's essentially four copies of HARP, looking at different portions of the spectrum with a narrower field of view.

I acted as a systems engineer, coordinating our engineering efforts at ESI with the team at [SDL](https://sdl.usu.edu/) working on the electronics.
I created a detailed week-by-week Gantt chart of the funding, design, prototyping, building, testing, and delivery of this 6-year-long, 20-million-dollar project.
I designed optomechanical subsystems, including a radiometric self-calibration system, a filter wheel, lens baffles, and sensor/prism holding.
I worked with our principal investigator, our thermal expert, 
and SDL to manage design tradeoffs between our different subsystems, and to estimate performance.
Due to small changes in the requirements since the previous HARP, I got involved in the optical optimization process. 
I worked with NASA systems engineers to meet various checkpoints in the study and negotiate the overall observatory design.

Initially, most of our estimates were based on some previous design work.
However late in the study, we found a serious problem.
Due to an oversight in some scaling laws, the mechanical layout of the system drove our thermal system up in mass,
to the point that we couldn't meet NASA's rough initial requirements.
Over the course of about three days, I took advantage of my ability to [hyperfocus](https://en.wikipedia.org/wiki/Hyperfocus) and redesigned the entire structure, thermal system, and internal layout.
This simplified the electronics and made the thermal system viable, essentially saving the study and greatly improving ESI's odds of securing the eventual contract.
Given the tight time constraints on this redesign, I don't think it would have been possible without hyperfocus.

With the radiometric self-calibration system, I misunderstood the design concept of a previous self-calibration system.
So, when I designed the new system, I accidentally used a different architecture which ended up being more efficient than the previous design.

I really enjoyed the autonomy I had with this project, and the experience of managing design constraints among many subject experts.
It was a great opportunity to stretch my wings as a designer and just come up with *anything* that might work.
NASA provided a clear schedule and set of requirements for the study, which avoided a lot of potential anxiety for me. 

## IMAP: Inverse Multi-Polarimetric Nephelometer
This constituted the vast majority of my work at [AirPhoton](https://www.airphoton.com/).
By measuring the intensity and polarization of scattered light at different angles and colors,
it measures aerosol and gas content as well as particle size and material.
The system was designed to operate outdoors continuously for years.

I did the conceptual design and detailed design of the core optics and setup the automation and firewall of the Linux system driving it.
I found a symmetry I could add (and another I could remove), which our principal investigator had not realized, to the optical layout which cut the overall size of the optics in half.
In the subassembly which collimates three coaxial laser beams of different wavelengths, I found an arrangement of apertures which collimates the beams and catches the diffracted light from each beam.
Importantly, this new arrangement was half the size of the previous design.
I designed parts to hold and route optical fibers throughout the instrument.
I designed pneumatic seals between all the parts of the core instrument.
I also designed a simple camera within the instrument.

I worked closely with another physicist, who did the benchtop validation of the optics I designed.
I also worked closely with another mechanical engineer, who designed the enclosure, 
the mounting for the supporting electrical and pneumatic equipment, and the mounting for the core instrument.
We had minimal supervision from our principal investigator.
We held check-ins every two weeks to make sure we were following his vision for the system and to pry design constraints out of him.

I really enjoyed the team dynamic on this project.
We worked autonomously and had a clear understanding of our responsibilities and system boundaries.
Thanks to carefully planned interfaces and [DFA](https://en.wikipedia.org/wiki/Design_for_assembly), when we needed to integrate the system, all the mechanics Just Worked™.
However, poor communication of project expectations and dishonesty about the schedule caused me a lot of anxiety and frustration.
In combination with the PI's refusal to accommodate my mental health needs (via remote work), 
this led to my resignation after the first few units shipped.

## AirHARP2: Fancy Cameras Crammed in a Box in an Airplane
This is a collection of custom and off-the-shelf instruments, packaged into independent modules which can be flown on many aircraft.
It will initially be flown on NASA's [Gulfsrteam V](https://airbornescience.nasa.gov/aircraft/Gulfstream_V_-_JSC) and [ER-2](https://www.nasa.gov/centers/armstrong/aircraft/ER-2/index.html) in support of [PACE](https://pace.gsfc.nasa.gov/).

The instruments are a SWIR camera, a polarimeter similar to [HARP][HARP], an off-the-shelf VNIR spectrometer, and a UV camera.
I designed the SWIR camera, and the majority of the structure.

The SWIR camera includes a lens assembly which is wide-angle on the subject end and telecentric on the sensor end.
It also includes a filter wheel.
The sensor is the same as what's used in [OreSat](https://www.oresat.org/).

## iTopie 3D Printer
After graduating, I had unrestricted access to a laser cutter for about two years.
That got me hooked on rapid prototyping and design.
I really wanted some kind of CNC machine of my own, but I couldn't afford a laser cutter.
So, I decided to build my own 3D printer.

The iTopie is an FDM printer I built following [a reprap design](https://reprap.org/wiki/ITopie).
The original design used an MDF frame cut on a CNC router.
I didn't have access to a CNC router. 
So, I modified the design to use thinner plates of laser-cut MDF, which I laminated together.

I sourced the COTS parts from AliExpress, because I had a tight budget.
I sourced the printed parts from 3D Hubs and a local makerspace. 

I did the assembly during COVID lockdown, and encountered a lot of design and fitment issues with the printed parts.
I was able to fix enough of the parts with epoxy and fiberglass to get it into a working state.
From there, I was able to redesign the problematic parts and print new ones.

At this point, the entire hotend is custom.
It's not perfect, but it's good enough for my purposes and quite reliable.

## Dragon 2 Docking System
I worked as a manufacturing engineer for the docking system of SpaceX's [Dragon 2 capsule](https://en.wikipedia.org/wiki/SpaceX_Dragon_2).
I mainly supported the In-Flight Abort (IFA) and Demo-2 units.
Unfortunately, I can only show NASA-released pictures here, since all my work was export-controlled and NDA-covered.

The IFA docking system was a mass simulator.
It was built out of old engineering-unit parts and purpose-built mass simulators.
So, I adapted manufacturing and testing work instructions from earlier units.

The Demo-2 unit had increased water-sealing requirements.
So, I spent a lot of time updating work instructions to include
RTV sealing and vacuum grease. 

A responsibility common to both units was addressing issue tickets.
Frequently, out-of-tolerance parts would be received, mistakes would be made during manufacturing,
and engineering errors would be found.
I would work with design engineers, quality engineers, an technicians to resolve these issues.

Most of the job boiled down to chasing down the "source of truth" for information,
tracking long lists of needed documentation changes,
and creating visual assembly instructions.

## Artificial Pancreas
At [Pacific Diabetes Technologies](https://www.pacificdt.com/), 
I worked on the mechanical design for a combined continuous glucose monitor and insulin pump.
I won't be sharing images of what I worked on, out of concern for the company.

I worked closely with an electrical engineer and chemist to spiral in on the overall form of the device.
Most of my time was spent designing the non-disposable electronics enclosure,
and the structure for the disposable sensor/fluid-path.
I prototyped designs using an [MJP](https://www.3dsystems.com/multi-jet-printing) printer.

## Fidget Toys
coming soon...

## OreSat: Oregon's First Satellite
coming soon...

## LV3: A Huge Amateur Rocket
coming soon...



[HARP]: https://esi.umbc.edu/harp2-project/
[ESI]: https://esi.umbc.edu/
